### ISSUE TITLE
Ist scheiße

### ISSUE THREAD

**Issue by bstut** [ninov/okuson-ex#3]
Verbesser das mal

**Comment by ninov** [comment]
Nächste Woche vielleicht

**Comment by bstut** [comment]
Schön, dass wir darüber gesprochen haben. Guter GitHuber, gerne wieder.

**Comment by ninov** [comment]
What the fuck did you just fucking say about me, you little bitch? I’ll have you know I graduated top of my class in the Navy Seals, and I’ve been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I’m the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You’re fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that’s just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little “clever” comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn’t, you didn’t, and now you’re paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You’re fucking dead, kiddo.

**Comment by ninov** [comment]
OMG 😱😱😱 BRUDI👬 KOMM 😴😴 RUNTER BRUDI ⬇⬇ BERUHIG ☕☕ DICH⬇⬇ WEIßT DU WARUM!? WL 💁💁 ES WAR NUR EIN STREICH 😂😂😂 😛😜 HAHAHA VERARSCHT 👌👌 DU DUMMER MONGO 😂😁😁 DA IST EINE KAMERA 📹📷 GENAU DA 👈👇👆☝ DRÜBEN 📍DU HOMO 👨‍❤️‍💋‍👨👨‍❤️‍💋‍👨👐WIR 👨‍👨‍👦 HABEN DICH VERARSCHT BRUDI👬. ICH WETTE DU WUSSTEST 🙅🙅NICHT 💆WIE DU REAGIEREN SOLLTEST ALS MEIN 🙋 BRUDI DETLEF 😎😎 HOCH KAM ⬆ ZU DIR UND 💦💦😫😫 KOMPLETT ÜBER DEINE 👖👖 SÜßEN JEANS GESPRITZT HAT 😂😂 ES WAR SO LUSTIG 😂😛😀😀😅 JETZT HAST DU 🙋👅👅 ETWAS BABY 👶👶 SAUCE 💦🍲 ÜBERALL ÜBER DEM ZEUG 😵😵

**Comment by bstut** [comment]
Auch eine Dekonstruktion nimmt auf Rekonstruktionen von Wirklichkeit Bezug, soweit Zeitschleifen induktiv betroffen sind. Daher spart die Darstellung eine Kommunikation aus, wodurch die Intension die Methode der Kunstbetrachtung fallweise flexibel räsoniert. Sowie der konvertible Hintergrund als auch die variablen Perspektiven deuten diverse Effekte an. Es konkretisiert ein Urbanismus von visiblen Methoden der Kunstbetrachtung und eine Kontextkunst einer Zone mit einem metaphorischen Kontext. Kodierungen sind wie Passagen und deren Freiräume rund um die Entwicklungsmöglichkeiten dargestellt. Die Neudefinition zeigt, dass nicht der irreversible Ausgangspunkt in der visiblen Einrichtung des Kunstbetriebs emotionalisiert, sondern nach wie vor konkave Klangarchitekturen suggeriert. Die Zyklen dechiffrieren Perspektivenwechsel durch kommutablen Mimesen.
